---
Resources:

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: ALBapp
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups: 
        - !ImportValue ALBSecurityGroup
      Subnets: 
        - !ImportValue SubnetIDPublicSubnet01
        - !ImportValue SubnetIDPublicSubnet02
        - !ImportValue SubnetIDPublicSubnet03
      Type: application

  HTTPlistener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: "redirect"
          RedirectConfig:
            Protocol: "HTTPS"
            Port: 443
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: "HTTP"
  
  TGApplication:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: True
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 3
      Matcher: 
        HttpCode: "200"
      Name: TG-App
      Port: 80
      Protocol: HTTP
      ProtocolVersion: HTTP2
      VpcId: !ImportValue VPCapp

Outputs:
  TGAssociationOutput:
    Description: TG
    Value: !Ref TGApplication
    Export:
      Name: TGAssociationOutput